# -*- coding: utf-8 -*-
"""Example1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p0C1OB4m0X_DAi5NlHmYW6hevGij2Il5
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')